meta_product_name: "YodaCity"
meta_title: "The simplicity of a bicycle, combined with the advantages of a motorcycle"
meta_description: "Mobility is evolving. Didn’t want to leave you all behind. Check out YodaCity here."
meta_image: "ogimage.png" # should exist in `app/assets/images/`
twitter_account: "YodaCity - It's like riding a bike, you never forget."   # required for Twitter Cards
